spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie_db
    username: root
    password: 123
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.github.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8088

mapper:
  mappers: com.github.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
